name: Testing

on:
  workflow_dispatch:
  release:
    types: [ released ]

jobs:
  tests:
    name: Tests
    runs-on: [self-hosted, Linux]

    services:
      database:
        image: mariadb:11
        env:
          MARIADB_DATABASE: test
          MARIADB_ALLOW_EMPTY_PASSWORD: false
          MARIADB_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: >-
          --health-cmd="mariadb-admin -u root --password=secret ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: 'shivammathur/setup-php@verbose'
        with:
          php-version: '8.2'
          extensions: sodium, zlib, dom, iconv, mbstring, filter, openssl, tokenizer, phar, :php-psr
          coverage: pcov
        env:
          runner: self-hosted

      - name: Check Database
        run: |
          php -r "mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT); \$mysqli = new mysqli('localhost:${{ job.services.database.ports[3306] }}', 'root', 'secret', 'test'); echo \$mysqli->host_info;"

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v3

      - name: Test
        run: |
          php application test --coverage

  lint:
    name: Lint
    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: 'shivammathur/setup-php@verbose'
        with:
          php-version: '8.2'
          extensions: sodium, zlib, dom, iconv, mbstring, filter, openssl, tokenizer, phar, :php-psr
        env:
          runner: self-hosted
          

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v3

      - name: Lint
        run: |
          ./vendor/bin/pint --test
    
